# Generated by Django 6.0.1 on 2026-02-14 14:52

from django.conf import settings
from django.db import migrations, models


def backfill_story_source(apps, schema_editor):
    StoryRatingComment = apps.get_model('gameplay', 'StoryRatingComment')
    source = (getattr(settings, 'FLASK_BASE_URL', '') or '').rstrip('/')
    StoryRatingComment.objects.filter(story_source='').update(story_source=source)


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_storyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storyratingcomment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storyratingcomment',
            name='story_source',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.RunPython(backfill_story_source, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='storyratingcomment',
            unique_together={('user', 'story_source', 'story_id')},
        ),
    ]
